work_dir: ./work_dir/recognition/ntu-xsub/ST_GCN_multi3_fix_3A_mstcn
# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: D:\PycharmProject\st-gcn数据集/data/NTU-RGB-D/xsub/train_data.npy
  label_path: D:\PycharmProject\st-gcn数据集/data/NTU-RGB-D/xsub/train_label.pkl
test_feeder_args:
  data_path: D:\PycharmProject\st-gcn数据集/data/NTU-RGB-D/xsub/val_data.npy
  label_path: D:\PycharmProject\st-gcn数据集/data/NTU-RGB-D/xsub/val_label.pkl

# model
model: net.st_gcn_multi3_fix_3A_mstcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial_3'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [20, 40]
#step: [10, 40, 50]

# training
device: [0]
batch_size: 8
test_batch_size: 8
#num_epoch: 80
num_epoch: 50

#start_epoch: 50
#weights: "D:/PycharmProject/st-gcn/work_dir/recognition/ntu-xsub/ST_GCN_normal_Afix/epoch50_model.pt."


