# weights: ./models/st_gcn.kinetics.pt
weights: D:\PycharmProject\st-gcn\work_dir\recognition\kinetics_skeleton\ST_GCN/epoch150_model.pt
model_fps: 30

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
    
# training
device: [0]