work_dir: ./work_dir/recognition/ntu-xsub/ST_GCN_TWO_STREAM

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150 
  data_path: ./data/Kinetics_origin/kinetics-skeleton/train_data.npy
  label_path: ./data/Kinetics_origin/kinetics-skeleton/train_label.pkl
test_feeder_args:
  data_path: ./data/Kinetics_origin/kinetics-skeleton/val_data.npy
  label_path: ./data/Kinetics_origin/kinetics-skeleton/val_label.pkl

# model
model: net.st_gcn_twostream.Model
model_args:
  in_channels: 3
  num_class: 400
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0]
batch_size: 32
test_batch_size: 32

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



